"""Runtime limits for web search."""

WEB_SEARCH_DEFAULT_RESULTS = 5
WEB_SEARCH_MAX_RESULTS = 5
WEB_SEARCH_MAX_CALLS_PER_CHAT = 2
WEB_SEARCH_MAX_QUERY_CHARS = 300
WEB_SEARCH_MAX_SNIPPET_CHARS = 800
WEB_SEARCH_MAX_FRESHNESS_DAYS = 3650

# Reserved for the M4 optimization milestone; M1 does not use retry or cache.
WEB_SEARCH_RETRY_COUNT = 1
WEB_SEARCH_CACHE_TTL_SECONDS = 900
WEB_SEARCH_CACHE_MAX_ENTRIES = 256
