-- Historical migration marker.
--
-- This file used to create only a partial agent_traces table and hard-coded
-- a USE statement.  Keep it as a record of the old migration number, but do
-- not execute it directly.  scripts/init_trace_db.py is the idempotent
-- initializer and upgrades both empty databases and this historical schema.
